version: "3.3"
services:

    web:
        build: 
            context: ./php   
            dockerfile: Dockerfile     
        container_name: php73
        depends_on: 
            - db
        ports:
            - "8000:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always        

    db:
        container_name: mysql8
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports: 
            - 6030:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf5_phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - 8080:80
        depends_on:
            - db

volumes:
    db-data: